### ISSUE TITLE
Implement Linkdrop Module for Gnosis Safe [Contracts]

### ISSUE THREAD

**Issue by amiromayer** [LinkdropHQ/linkdrop-monorepo#208]
# Description

The tech spec can be found here: 
https://docs.google.com/document/d/1K-x0W584sv1GawA8nSblbhM-6jtuyUkI_3jKXe4OMiE/edit#

# Subtasks included

- [x] Create a new repo for Gnosis Safe Module
- [x] Implement Linkdrop Module
- [x] Cover the functionality with unit tests

# Definition of done
Gnosis Safe's users are able to connect Linkdrop Module and send and receiver digital assets via shareable links

# Reviewer
