### ISSUE TITLE
Fix bugs on the backend

### ISSUE THREAD

**Issue by amiromayer** [LinkdropHQ/linkdrop-monorepo#215]
# Description
Fix couple of small bugs that were causing issues on the backend

# Subtasks included

- [x] Fix bug with ERC721 claim
- [x] Fix bug with URL parsing
- [x] Make sure all config variables are present

# Definition of done
All mentioned bugs are fixed

# Reviewer
