### ISSUE TITLE
Refactor scripts to make compatible with new SDK and Dashboard contracts

### ISSUE THREAD

**Issue by amiromayer** [LinkdropHQ/linkdrop-monorepo#271]
# Description
Update scripts

# Subtasks included

- [x] Update existing scripts
- [x] Add new `deploy-registry` script
- [x] Test scripts working

# Definition of done

# Reviewer
@Dobrokhvalov
