### ISSUE TITLE
Align colors & contact on first dashboard page

### ISSUE THREAD

**Issue by Kisgus** [LinkdropHQ/linkdrop-monorepo#362]
# Description

We use different colors on linkdrop.io / dashboard.linkdrop.io

![Screen Shot 2019-08-12 at 12 38 05 PM](https://user-images.githubusercontent.com/18598519/62923975-5d138e80-bdaf-11e9-99b1-2e936590cb42.png)

vs

![Screen Shot 2019-08-12 at 12 50 55 PM](https://user-images.githubusercontent.com/18598519/62923981-60a71580-bdaf-11e9-8fa1-66996092042c.png)

# Subtasks included

- [ ] Change "Conact" to "Contact Us"
- [ ] Make blue outlined buttom as below

![Screen Shot 2019-08-13 at 9 49 59 AM](https://user-images.githubusercontent.com/18598519/62924170-d4492280-bdaf-11e9-89c2-b3d87f3bd872.png)

- [ ] When clicking link to https://linkdrop.io/sales/

# Definition of done

# Reviewer
