### ISSUE TITLE
Add callback data for v2 contracts

### ISSUE THREAD

**Issue by amiromayer** [LinkdropHQ/linkdrop-monorepo#591]
# Description
Currently, we need to deploy custom versions of linkdrop contracts for specific use-cases that require custom external functions to be called prior to or after the execution of claim function. We need to add support for passing in the callback data to be called inside the claim function to unify the linkdrop mechanism for a broader range of use-cases.

# Subtasks included

- [x] Add callback data support to contracts
- [x] Cover contract changes with tests
- [x] Add callback data support to SDK
- [x] Modify scripts to support callback data
- [x] Add callback data support to the Relay Service

# Definition of done
It's possible to pass custom data to be called within the claim transaction.

# Reviewer
